### ISSUE TITLE
Cant pass custom Ref from Functional component

### ISSUE THREAD

**Issue by WhoIsDT** [Andarist/react-textarea-autosize#250]
So i'm using 'hooks'

```
function TaskColumn({ title, children }) {
  const taskFieldRef = useRef()
```

Then in rendrer i'm trying to pass my ref

```
<TextareaAutosize
              innerRef={taskFieldRef}
              className='AddTaskField'
              value={newTaskField.value}
              placeholder={newTaskField.config.label}
              onChange={event => fieldChangedHandler(event)}
            />
```

But its not working. Can you maybe explain why and how to do it with hooks?

**Comment by Andarist** [comment]
It's `inputRef`, not `innerRef`.

**Comment by xuan9230** [comment]
It's still failing. Says `Uncaught TypeError: _this.props.inputRef is not a function`. You got a ref object not a function from the `useRef` hook.

**Comment by Andarist** [comment]
Could you prepare a runnable repro case?

**Comment by Andarist** [comment]
I've released the new major version which uses `forwardRef` under the hood so you should be able to just use `ref` prop now without any problems.
