### ISSUE TITLE
emit ts definitions

### ISSUE THREAD

**Issue by dipunm** [Andarist/react-textarea-autosize#262]
Reproduce:
```js
// Using typescript:
const MyTextareaAutoSize = React.forwardRef<HTMLTextAreaElement>((props, ref) => {
    return (<TextareaAutoSize {...props} inputRef={ref} />);
})
```
The above code fails to compile because `@types/react-textarea-autosize` is old and does not declare support for null. Currently, I have to work around this with:
```js
    return (<TextareaAutoSize {...props} inputRef={ref || undefined} />);
```

Since this is a TS project, could we package definition files into the release?

**Comment by Andarist** [comment]
Well - this package was not written in TS. I had an unpublished rewrite to TS available on master though 😅 and you have pushed me to finish the work and release v8: https://github.com/Andarist/react-textarea-autosize/releases/tag/react-textarea-autosize%408.0.0 . Enjoy 🎉

**Comment by EvidentlyCube** [comment]
@Andarist I believe you also need to add `types` to `package.json`. When I added `"types": "dist/declarations/src/index.d.ts"` IntelliJ now recognizes the package.

Also it appears `TextareaAutoSize` type is not emitted anywhere.

**Comment by Andarist** [comment]
> @Andarist I believe you also need to add types to package.json. When I added "types": "dist/declarations/src/index.d.ts" IntelliJ now recognizes the package.

It seems like IntelliJ's problem - this is both recognizable by TypeScript itself and some of the other editors.

> Also it appears TextareaAutoSize type is not emitted anywhere.

It's not a type - it's a component. Not sure how you would like to use it - you can probably do smth like `React.FC< TextareaAutosizeProps>`
