### ISSUE TITLE
ref in ts does not support focus()

### ISSUE THREAD

**Issue by Manonisch** [Andarist/react-textarea-autosize#268]
Version react-textarea-autosize: 8.0.1.

Hi, we are currently using textarea in a typescript react project. Trying to call focus() on the textarea ref component leads to lint returning a type error `Property 'focus' does not exist on type 'TextareaAutosize'.`

Ref is being used in a functional component pattern:

```
import Textarea from 'react-textarea-autosize';

function component(){

  const myRef = useRef<Textarea | null>(null);

  return (
    <Textarea
     ref = {myRef}
    />);
```

Focus is being called on ref with
`
myRef.current?.focus();
`

**EDIT:** On further inspection, this seems to be not a problem with this library. We are currently nesting the TextArea component in a styling layer, which also uses forwardRefs, thereby making the outer TextArea component its inner ref.

**Comment by Andarist** [comment]
What you have imported as `Textarea` is not a type - I suspect that you have `@types/react-textarea-autosize` installed where this is defined as a class which is acceptable for TS in types position.

The correct way of using this in v8 is to uninstall `@types/react-textarea-autosize` if you have it installed and do this:
```js
import * as React from 'react';
import Textarea from 'react-textarea-autosize';

function MyComponent() {
  const myRef = React.useRef<HTMLTextAreaElement>();
  return <Textarea ref={myRef} />;
}
```
