### ISSUE TITLE
Please publish 8.0.1 to npm

### ISSUE THREAD

**Issue by f0rmat1k** [Andarist/react-textarea-autosize#272]

**Comment by f0rmat1k** [comment]
sry

**Comment by f0rmat1k** [comment]
@Andarist btw you didnt push 8.x.x tags to github

**Comment by Andarist** [comment]
They are pushed, but in a different format and they don't show up in a dropdown. Gonna fix it in a moment as the fix for this has been released in a tool I use to publish this package: https://github.com/atlassian/changesets/pull/376
