### ISSUE TITLE
[IMPORTANT] Do not use v8.1.0, it's broken!

### ISSUE THREAD

**Issue by emdotem** [Andarist/react-textarea-autosize#281]
I already addressed the issue in #280 

In the latest release there is a typo we didn't spot before. 
Fixed and tested.

**Comment by Andarist** [comment]
Fix should be released in a moment

**Comment by emdotem** [comment]
As long as v8.1.0 is the latest version available I'd leave this open.

**Comment by Andarist** [comment]
At the time Ive closed this issue the release was already happening, so i’ve just assumed that it would go smoothly

**Comment by Andarist** [comment]
Ah, it failed on linting - sorry. It was already past midnight when I was handling this and had to go to sleep.
