### ISSUE TITLE
This is NOT an issue, it's a CSS Feature

### ISSUE THREAD

**Issue by m-reyes-h** [Andarist/react-textarea-autosize#291]
You can create a grow up text area with this CSS snippet

```

.DivTextAreaWrapper {
  position: relative;
  height: 200px;
}

textarea {
  position: absolute;
  bottom: 0;
  resize: none;
}
```

Hope this can help others

**Comment by Andarist** [comment]
Thanks for putting this for others searching for similar solutions - as this is not an issue I'm going to close it though. It will still be available for anyone searching through issues.
