### ISSUE TITLE
ref doesn't accept a function as ref?

### ISSUE THREAD

**Issue by gperez-10pines** [Andarist/react-textarea-autosize#300]
Autosize is not working when I pass a function instead of a ref object.

However, React does support functions. And react-textarea-autosize documentation states it does too:
`<TextareaAutosize ref={(tag) => (this.textarea = tag)} />`

Looking at the code, there's the assumption that it's an object with the `current` prop. So, no check for functions

```
  componentDidMount() {
    ...
    if (typeof maxRows === "number" || async) {
      ...
      setTimeout(
        () => this.textarea.current && autosize(this.textarea.current)
      );
    } else {
      this.textarea.current && autosize(this.textarea.current);
    }

    if (this.textarea.current) {
      this.textarea.current.addEventListener(RESIZED, this.onResize);
    }
  }
```

Also, the interface is:
```
    interface RefObject<T> {
        readonly current: T | null;
    }
```

Any clue how to make it work with a function? Am I missing something?

**Comment by Andarist** [comment]
AFAIK functions are accepted as well. 

Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by gperez-10pines** [comment]
Good call. 

And actually, works fine in codepen:
https://codepen.io/gperez10pines/pen/xxERVQz?editors=1010

I'll try to reproduce the error though. And then I'll close the ticket if I can't. 

Thanks.

**Comment by gperez-10pines** [comment]
Wait a second, I was able to reproduce it. It's a version problem.

Try @7.0.0 and it fails. Works with @7.1.0

**Comment by Andarist** [comment]
Can u repro with 7.0.0? I would appreciate a repro case for that even if it works in 7.1.0

**Comment by gperez-10pines** [comment]
Yeah, same link. 
codepen.io/gperez10pines/pen/xxERVQz?editors=1010

In the second line change @7.0.0 to @7.1.0 to compare

**Comment by Andarist** [comment]
Hm, not sure how to repro the problem given that link. I've tried with 7.0.0 and the ref callback seems to be invoked correctly:
<img width="1406" alt="Screenshot 2020-12-15 at 22 39 12" src="https://user-images.githubusercontent.com/9800850/102276008-80f85e80-3f26-11eb-91e0-f5a48c7b635e.png">

**Comment by gperez-10pines** [comment]
It is called, I think React guarantees that. But try the textarea. It won't grow. Then try with 7.1.0 version and it will work. The functionality is the key here. Passing a function, it breaks.

Also, if you compare the files, 7.0.0 was like this, using `this.textarea.current`:

```
  componentDidMount() {
    ...
    if (typeof maxRows === "number" || async) {
      ...
      setTimeout(
        () => this.textarea.current && autosize(this.textarea.current)
      );
    } else {
      this.textarea.current && autosize(this.textarea.current);
    }

    if (this.textarea.current) {
      this.textarea.current.addEventListener(RESIZED, this.onResize);
    }
  }

```

and 7.1.0 is like this:

```
  componentDidMount() {
    ...
    if (typeof maxRows === "number") {
      this.updateLineHeight();
    }

    if (typeof maxRows === "number" || async) {
      ...
      setTimeout(
        () => this.textarea && autosize(this.textarea)
      );
    } else {
      this.textarea && autosize(this.textarea);
    }

    if (this.textarea) {
      this.textarea.addEventListener(RESIZED, this.onResize);
    }
  }
```

Meaning, in the the first chunk of code `this.textarea.current` used to evaluate to `undefined`, because `.current` property of a function is `undefined`.

**Comment by Andarist** [comment]
This codepen is using `react-autosize-textarea` and this repository contains `react-textarea-autosize` 😅
