### ISSUE TITLE
Unexpected caret shows up on mobile android device

### ISSUE THREAD

**Issue by taejs** [Andarist/react-textarea-autosize#302]
### Steps to reproduce
codesandbox url
https://codesandbox.io/s/throbbing-water-9b39o

### Describe the bug
caret shows up on the first load.
look at the gray caret of input fade in and out.
I've tested 'jquery-autosize' library, but caret doesn't appear.

![codesandbox](https://user-images.githubusercontent.com/41318449/104560870-de004500-5689-11eb-987e-222999163c85.gif)

### Environment
emulator 
- Chrome / Pixel 2 API - Android 10 

real device
- Chrome / Samsung Galaxy S20+  - Android 10
- Samsung Internet / Galaxy S20+  - Android 10
- Chrome / Samsung Galaxy Note 10  - Android 9
- Chrome / Samsung Galaxy S9+  - Android 9

**Comment by Andarist** [comment]
If this is an issue for you I would suggest investigating it on your own because I doubt that I will have time to do it.

**Comment by taejs** [comment]
I investigated it, It's not a text cursor. It's scrollbar of textarea.
Is there any solution for it?

**Comment by Andarist** [comment]
I can only repeat myself - I have no idea why this happens so if this is an issue for you I would suggest investigating it **further** on your own because I doubt that I will have time to do it.
