### ISSUE TITLE
Doesn't work inside a tippyjs popover

### ISSUE THREAD

**Issue by maxsalven** [Andarist/react-textarea-autosize#303]
If the textarea is inside a tippyjs popover, the height and autoFocus do not take effect when rendering:
https://codesandbox.io/s/romantic-star-dp9qr

**Comment by Andarist** [comment]
This library somehow initially renders the textarea detached from the DOM - I suspect that's the culprit of the problem and as such, I don't think it's on our side to fix this. You might need to figure out how to integrate both on your own.
