### ISSUE TITLE
minRows concept is confusing

### ISSUE THREAD

**Issue by HasanCanUgurlu** [Andarist/react-textarea-autosize#304]
So I'm trying to achieve having a textarea that has 15 rows when no input, expands to a max row when it gets input. TextareaAutosize expanses as intended but It seems like it only has 1 row when empty. I tried playing with minRows and maxRows, nothing changes. I believe this is an easy solution, I'd appreciate some help. Thank you!

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by HasanCanUgurlu** [comment]
Hey sorry about that, I'm new to the community. I have this [codebox](https://codesandbox.io/s/brave-jepsen-7dpwe?file=/src/App.js) that explains the issue that I have. Maybe I didn't get the right concept of using max-min rows ¯\_(ツ)_/¯

Thank you for your time.

**Comment by Andarist** [comment]
`minRows` and `maxRows` are **props** (and not style properties), take a look at the corrected example: https://codesandbox.io/s/thirsty-banach-vo287

**Comment by HasanCanUgurlu** [comment]
(－‸ლ) I got it now, thank you again.
