### ISSUE TITLE
Feature request `initialHeight` or `minHeight`

### ISSUE THREAD

**Issue by albertcito** [Andarist/react-textarea-autosize#314]
I'm setting the `initialHeight` or `minHeight` with `minRows={2}` but it's not exactly. There is a possibility to add an initial height.

**Comment by Andarist** [comment]
You can provide `style={{ height: 10 }}` for this purpose

**Comment by albertcito** [comment]
I added `style={{ height: 48 }}`  but the value is replaced by `style="height: 32px !important;"`. Also, I'm using TS so I tried to add `minHeight` but it is not allowed.

**Comment by Andarist** [comment]
Could you describe your use case? It sounds like you want a different height than computed through rows - this ain't possible and I'm not sure why you'd like it.

**Comment by albertcito** [comment]
The idea that the `min-height` could be `48px`. But with `minRows={2}` is `height: 56px !important;`. So I don't have way to set that value as `min-height`

[<img width="654" alt="Screen Shot 2021-03-24 at 5 46 30 PM" src="https://user-images.githubusercontent.com/1768483/112387984-df24a280-8cc8-11eb-966d-814bf550a7e6.png">](https://play.tailwindcss.com/NagUN0sheX) 
[source here](https://play.tailwindcss.com/NagUN0sheX)

**Comment by Andarist** [comment]
I guess we could remove this restriction on `style.minHeight`:
https://github.com/Andarist/react-textarea-autosize/blob/58c9807645dceb9034b733d9cb63aa66df2364b0/src/index.tsx#L47-L51

Feel free to prepare a PR.

**Comment by eizci** [comment]
as a workaround;
`textarea{
    min-height: 0!important;
}`

**Comment by sdimitris** [comment]
Have thte same problem

```
          <TextareaAutosize
            className="focus:pointer-events-auto border-1 rounded-sm border-[#434343] bg-[#141414] text-white hover:border-primary-accent"
            style={{ width: 365,height: 200 }}
            value={newComment}
            placeholder={"Comment"}
            onChange={(e) => setNewComment(e.target.value)}
          ></TextareaAutosize>
```
Only width works. The height value is replaced with "height: xxx px !important"

**Comment by albertcito** [comment]
I created a [component](https://github.com/albertcito/textarea-autosize-reactjs) to work with auto-size. Maybe you can use the same library that I used to fix all your issues.

[autosize](https://github.com/jackmoore/autosize)

**Comment by addamove** [comment]
> You can provide `style={{ height: 10 }}` for this purpose

It's not working
