### ISSUE TITLE
value and defaultValue props

### ISSUE THREAD

**Issue by arifemir** [Andarist/react-textarea-autosize#317]
No value and defaultValue props in component, how can i use with northstar textArea component

**Comment by Andarist** [comment]
The issue is so vague that I don't understand the question

**Comment by arifemir** [comment]
There is typescript error in the module and and creates this "default text area props cannot be given" problem

this code not run bec TS error for value props
`
<TextareaAutosize
  value={this.state.sharedNoteText}
  className='text-area-auto-size'
  cacheMeasurements
  onHeightChange={(sharedNoteHeight) => this.setState({sharedNoteHeight})}
 />
`

I used to have compulsory @ts-ignore
`
<TextareaAutosize
  //@ts-ignore
  value={this.state.sharedNoteText}
  className='text-area-auto-size'
  cacheMeasurements
  onHeightChange={(sharedNoteHeight) => this.setState({sharedNoteHeight})}
 />
`

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by arifemir** [comment]
I apologize for my inexperience, i am fixed and here is example for react-textarea-autosize with fluentui/northstar 
https://codesandbox.io/s/sleepy-easley-mt0ef?file=/src/App.js

**Comment by Andarist** [comment]
I still don't know what the issue is/was. This codesandbox doesn't use TS at all - and from what I got your issue was about TS.

**Comment by arifemir** [comment]
i am sorry there is no issue ts implementation btw;
https://codesandbox.io/s/recursing-hermann-17jf4?file=/src/App.tsx
