### ISSUE TITLE
How can I make this component to start resizing upwards after resizing downwards to a certain height on screen?

### ISSUE THREAD

**Issue by awadesmoline** [Andarist/react-textarea-autosize#320]
Hi, please i'd like to make this textarea to resize downwards up to a certain point, and then start resizing upwards, so that the cursor never gets hidden from the viewport. Any idea how I can do this. I want the cursor to be a like about 100px from the bottom of the viewport and never go below.

My textarea starts with the following height. Resulting from a minRows of 5.

<img width="1247" alt="Screenshot 2021-04-29 at 17 17 02" src="https://user-images.githubusercontent.com/25609312/116583894-b9656b80-a90e-11eb-9a87-c6effe24c72d.png">

thanks in advance.

**Comment by Andarist** [comment]
You could try manipulating `maxRows` - nothing will be added to the core of this component to support this, so if you want to use then you will have to just use what's already available.
