### ISSUE TITLE
Allow TextareaAutosize to use min-height instead of height

### ISSUE THREAD

**Issue by LoganDark** [Andarist/react-textarea-autosize#332]
I want the textarea to always contain the text, but I also want it to be able to grow since it's in a flex container.

Right now `'height'` is hardcoded into the library:

https://github.com/Andarist/react-textarea-autosize/blob/0d7ac21f1dadf1fb9070aea5f76f20b7ce2f24bc/src/index.tsx#L81

I just want to be able to change this to `min-height`

**Comment by Andarist** [comment]
I think it should be possible to just use `minRows` in your case. If it's not sufficient please prepare a codesandbox reproducing the issue that you are facing.

**Comment by LoganDark** [comment]
> I think it should be possible to just use `minRows` in your case. If it's not sufficient please prepare a codesandbox reproducing the issue that you are facing.

I think you completely misread my issue. Right now you set the height property to ensure that the textarea does not change from the height you want, I want an option to set the min-height property so that it can get bigger, but not shrink

**Comment by Andarist** [comment]
And I think that `minRows` should do exactly that - it would still set `height` on the element but it would allow it to grow.

**Comment by LoganDark** [comment]
> And I think that `minRows` should do exactly that - it would still set `height` on the element but it would allow it to grow.

That's my issue - the setting of `height` keeps it completely rigid, I cannot grow the textarea via flexbox or other means, which is what I'm trying to do. I have two elements side by size and I want the textarea to either grow the height of the flex container, or be the height of the flex container. As in, the *minimum height* of the textarea should be the number of rows it currently contains - not the *final height*.

**Comment by Andarist** [comment]
I've used this component successfully in a flex container. I'd like to understand your issue better first before jumping to any conclusions - that's why I've asked about a codesandbox demonstrating the problem

**Comment by LoganDark** [comment]
> I've used this component successfully in a flex container. I'd like to understand your issue better first before jumping to any conclusions - that's why I've asked about a codesandbox demonstrating the problem

Weird, for some reason https://b6eo8.csb.app/ works correctly - apparently your detection works properly there, but not in my live app. The only difference I can think of is the live app uses scoped CSS instead of style attributes.

IMHO, this is even more reason to support min-height, because you already support this functionality... you just emulate it using `height`. :/

**Comment by Andarist** [comment]
I'm afraid that I can't justify making any changes to this library without understanding how this affects your use case.

**Comment by LoganDark** [comment]
> I'm afraid that I can't justify making any changes to this library without understanding how this affects your use case.

My use case is for a Markdown editor, where the textarea and preview are the same height. You can see in the codesandbox what I mean. If the preview is long the textarea grows, if the textarea is long the container grows. But in my application the textarea doesn't grow. For some reason it stays stuck at the text height and won't grow any larger. This is because your library tries to precisely control the height, so the textarea won't grow unless the library realizes, which... it doesn't seem to be doing for some reason.

I don't really know why it's so hard to explain this but I know how to fix it. Because manually changing `height` to `min-height` in the style attribute works. And I don't know why it works fine in the codesandbox, but not a real app. Here is my HTML structure:

![image](https://user-images.githubusercontent.com/4723091/126962926-e5dd3e13-ff6a-43b5-9c5d-681af2c40b35.png)
 
The top level div is a flex container. Both the textarea and the preview are flex items with `flex: 1 1 0%` set. But in cases where the preview is taller than the textarea, the textarea does not grow. It stays shrink wrapped around the text. This is the bug that min-height would fix, because the textarea would be able to expand to fill the vertical space

**Comment by Andarist** [comment]
What you can do is try to bisect the issue to demonstrate it, in an isolated form, on the codesandbox. I don't believe in providing more options without knowing the full context behind it. If it doesn't work in your app then is a reason for that and it should be found first and then evaluated. I'm not necessarily saying that the proposed solution is wrong but until a repro case is found I can't see the full picture that is needed for me to justify making any changes here.

**Comment by LoganDark** [comment]
I have fixed this issue in a fork and no longer need upstream approval.

I hope you at least realize @Andarist that expecting this library to get layout right in all cases is not sustainable and will inevitably result in edge cases such as this one. I would highly recommend moving to min-height (and max-height if maxRows is specified) rather than expecting height to be completely infallible. Thank you for considering my issue and I am sorry that I was not able to provide enough detail.
