### ISSUE TITLE
Connect label with textarea

### ISSUE THREAD

**Issue by Silvano14** [Andarist/react-textarea-autosize#339]
I treid to connect by htmlFor a label with your TextareaAutosize, but I can't. 
Maybe exist a method to do it? 

I'm using version 8.3.3
I have Ubuntu system 21 
I'm testing with chrome

**Comment by henrywoody** [comment]
What have you tried? Can you include your code?

**Comment by Silvano14** [comment]
I just try it and it seems work, maybe the problem is only on linux. 

Below is my test
https://codesandbox.io/s/keen-hertz-quiwqy?file=/src/App.js

I close che issue
