### ISSUE TITLE
Couldn't install npm i react-textarea-autosize React"^18.1.0"

### ISSUE THREAD

**Issue by booandrew** [Andarist/react-textarea-autosize#343]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/63796184/168536038-e82e6ff9-cef9-4b43-82ab-acd42bea148f.png">

**Comment by DavidChouinard** [comment]
@Andarist looks like `master` fixes this, is it possible to release new version?

**Comment by Andarist** [comment]
A new version should become available shortly.
