### ISSUE TITLE
When you limit the height of the div outside a <TextareaAutosize/>, the textarea component becomes scrollable. 

### ISSUE THREAD

**Issue by amarnath-cohesive** [Andarist/react-textarea-autosize#358]
The expected result is for the external div to become scrollable, and the textarea to wrap all of the text present. PFA a sandbox with the demo. Also, once you have exhausted the available height for a textarea, if you have another textarea below it, the latter becomes diminished in height. 
https://codesandbox.io/s/summer-violet-bv33zq?file=/src/App2.jsx

**Comment by Andarist** [comment]
This is caused by your flex layout. I'm not exactly sure how to fix this but it's beyond the responsibilities of this component.
