### ISSUE TITLE
TypeError in version `8.4.1`

### ISSUE THREAD

**Issue by emmenko** [Andarist/react-textarea-autosize#368]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/1110551/226882174-eb43bebd-869b-4656-8a49-9b724e410a63.png">

Updating from version `8.4.0` to `8.4.1` causes an error in our tests. Maybe related to the changes in #362 ?

cc @ArnaudRinquin

**Comment by Andarist** [comment]
Yes, it's likely related. JSDom doesn't implement `document.fonts` - that alone I don't classify as a problem. The runtime code of the library doesn't have to support JSDom quirks. However, the README currently states that:
> This module supports IE9 and above.

And `document.fonts` is not available in IE. So I would accept a PR fixing this.

**Comment by soulakmartin** [comment]
+1

I have a same issue.

**Comment by ArnaudRinquin** [comment]
Sorry folks, only noticed this issue now. Proposed something that should fix this.
