### ISSUE TITLE
package gets resolved as commonjs from an esm project

### ISSUE THREAD

**Issue by Tronikelis** [Andarist/react-textarea-autosize#372]
Hey, I recently stumbled upon some weird behavior while using another library that uses your package, the library is https://github.com/nextui-org/nextui v2 

I am kinda out of options, cause I am struggling to figure this out myself

I am using ts + vite + vite-plugin-ssr with default configs
But got the same behavior using next.js as well

While bundling the project I got an error that `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

I created an issue for this https://github.com/nextui-org/nextui/issues/1160

The gist of it is that your package gets resolved as commonjs from an esm project (vite uses esm by default either way I think) and then the cjs exports the component as `module.exports.default = ` but esm treats default exports from commonjs as `module.exports = ` not as `module.exports.default = ` 

So when nextui-org imports your package it gets imported as `{default: ..component..}` which is not a component and it fails

More info https://github.com/nextui-org/nextui/issues/1160

I am not sure if this is because of a bad vite config, but I don't think so, because I checked your package with https://arethetypeswrong.github.io/?p=react-textarea-autosize%408.4.1 and just as I thought `node16-esm` resolves your package to cjs:

<details>
<summary>Screenshot from the website</summary>

![firefox_EuObXPe0Op](https://github.com/Andarist/react-textarea-autosize/assets/56039679/518fe9bf-2fd1-4e81-a3c4-e0c09656f8d5)

</details>

Thanks

**Comment by Andarist** [comment]
Could you try out the version from this PR: https://github.com/Andarist/react-textarea-autosize/pull/373 ?

**Comment by Andarist** [comment]
🙈 I forgot to commit those two files. Could you try again now?

**Comment by Tronikelis** [comment]
Now it builds successfully for me 🚀
