### ISSUE TITLE
Invalid exports in package.json

### ISSUE THREAD

**Issue by berekuk** [Andarist/react-textarea-autosize#379]
`exports["."].browser.import` points to `./dist/react-textarea-autosize.browser.cjs.mjs`, which doesn't exist.

There are a few other paths in `exports` which don't exist, but I'm having problems with that one (in Jest environment with ESM).

**Comment by Andarist** [comment]
Thank you for the report! I located the problem and I'm fixing it [here](https://github.com/preconstruct/preconstruct/pull/567)
