### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by gvillo** [Andarist/react-textarea-autosize#406]
Hi, it would be awesome to add react 19 support since it's stable and launched now. I am using Mantine and this is one of the deps that it's raising a warning because of peerDeps

**Comment by nightness** [comment]
Yeah, I almost tried to make a PR to update the peer deps because there haven't been updated in forever until I realized, same author... So I've seen that this package support react 19, but the two peer deps do not yet...

    "use-composed-ref": "^1.3.0",
    "use-latest": "^1.2.1"
    
  Thanks!

**Comment by Andarist** [comment]
All of those should be resolved now.

**Comment by nightness** [comment]
> All of those should be resolved now.

I don't see a release of this package using the newer version of the dependencies.

**Comment by Andarist** [comment]
Isnt this available on npm? https://github.com/Andarist/react-textarea-autosize/pull/405

**Comment by nightness** [comment]
I'm not a npm expert, and I haven't tested my assumption here (I can't atm)...

I don't think it's going to update the peer deps in a project using this package unless you set the minimum versions of the peer deps in this project to the new versions that were just released for the two peer dependencies.
